# Generated by Django 3.2.8 on 2023-07-30 09:00

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('image', models.ImageField(default='blog_images/blog-1.jpg', upload_to='blog_images')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
